"""create_passage_model

Revision ID: 6fb6ae9aa084
Revises: b9f3ae593c8e
Create Date: 2024-01-09 16:06:35.971543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "6fb6ae9aa084"
down_revision = "b9f3ae593c8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passage",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("book_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("verses", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("book_id", "verses"),
    )
    op.create_index(op.f("ix_passage_id"), "passage", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_passage_id"), table_name="passage")
    op.drop_table("passage")
    # ### end Alembic commands ###
